### PR TITLE
Fixes for subscribing/unsubscribing, new chat format and filtering features

### PR DESCRIPTION
**Pull request by LordBoos**
- Fixes for subscribing/unsubscribing on join/quit
- Add possibility to use in-game chat format for messages sent to and from discord (players will see exactly the same chat format for messages send from discord and from game)
  - On the first message sent in-game, the users format is saved and later used as format for messages sent from discord by user with the same nickname.
  - Messages sent in-game are formated in the same way in discord chat (minus colors).
- Add posibility to specify adnim chat channel prefix, so admin messages are not sent to discord

### CODE REVIEW

**Comment by LordBoos** [comment]
- Add option to also show messages from discord in server console/log

**Comment by manuelgu** [comment]
Thanks for the PR and sorry for the delay! Will look through the changes later this week.

**Comment by LordBoos** [comment]
Well I'm not in hurry as I've compiled it and already using it myself 😄

**Comment by LordBoos** [comment]
This also fixes the https://github.com/manuelgu/DiscordMC/issues/16

**Pull request merged**
